services:
  frontend: 
    container_name: frontend-coleta
    build: .
    ports:
      - 5173:5173
  
  backend: 
    container_name: api
    image: vitorlassen/back-coleta
    ports:
       - 3000:3000 

  db: 
    container_name:  banco
    image: postgres
    environment:
      - POSTGRES_PASSWORD=P@ssword
    ports: 
      - 5432:5432